In [1]:
import numpy as np
import pandas as pd

In [2]:
#Question 1
#The version of NumPy installed
np.__version__

'1.23.2'

In [ ]:
#getting the Car price dataset with 'wget' command
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

In [3]:
#Getting the data
data = pd.read_csv("data.csv")

In [4]:
data

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [5]:
#Question 2
#How many records are in the dataset?
#Here you need to specify the number of rows.
data.shape[0]

11914

In [15]:
#Question 3
#Which are the most frequent car manufacturers (top-3) according to the dataset?
data.Make.value_counts().head(3).index

Index(['Chevrolet', 'Ford', 'Volkswagen'], dtype='object')

In [16]:
#Question 4
#What's the number of unique Audi car models in the dataset?
len(data['Model'][data['Make'] == 'Audi'].value_counts())

34

In [17]:
#Question 5
#How many columns in the dataset have missing values?

#ANSWER: the sum of the elements of the array formed based on the count of the number of cells
# with zero values in each of the columns of the initial dataset!!!
data.isnull().sum().value_counts()\
    [data.isnull().sum().value_counts().index != 0].values.sum()

5

In [18]:
#Question 6
#1) Find the median value of "Engine Cylinders" column in the dataset
data['Engine Cylinders'].mean()

5.628828677213059

In [19]:
#2) ВАРИАНТ №2 Calculate the most frequent value of the same "Engine Cylinders"
most_freq_ec_amount = data.sort_values(by='Engine Cylinders', ascending=False)['Engine Cylinders']\
    .value_counts(ascending=False)
most_freq_ec_amount

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [20]:
data.sort_values(by='Engine Cylinders', ascending=False)['Engine Cylinders'].value_counts(ascending=False).index[0]

4.0

In [21]:
#3) Use the fillna method to fill the missing values in "Engine Cylinders"
#   with the most frequent value from the previous step

In [22]:
#average value of Engine Cylinders, calculated taking into account records in the table,
# that have missing values in this column
mean_ec = data['Engine Cylinders'].mean().round(2)
mean_ec

5.63

In [24]:
#average value of Engine Cylinders, calculated taking into account the filling of missing values
# calculated in the previous step(#2) by 'most_freq_ec_amount' (the most frequent value of "Engine Cylinders")

mean_ec_after = data['Engine Cylinders'].fillna(most_freq_ec_amount).mean().round(2)
mean_ec_after

#Question 6 - Answer: No, the median value of "Engine Cylinders" hasn't changed!

5.63

In [25]:
#Question 7

In [26]:
#7.1 Select all the "Lotus" cars from the dataset
data[data.Make == 'Lotus'].head()

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

In [27]:
#7.2 Select only columns "Engine HP", "Engine Cylinders"
data[data.Make == 'Lotus'][['Engine HP', 'Engine Cylinders']]

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0
3917      189.0               4.0
3918      217.0               4.0
3919      217.0               4.0
4216      350.0               8.0
4217      350.0               8.0
4218      350.0               8.0
4257      400.0               6.0
4258      400.0               6.0
4259      276.0               6.0
4260      276.0               6.0
4261      276.0               6.0
4262      345.0               6.0
4263      345.0               6.0
4264      276.0               6.0
4265      345.0               6.0
4266      276.0               6.0
4267      345.0               6.0
4268      276.0               6.0
4292      257.0               4.0
4293      240.0               4.0
4294      240.0               4.0
4295      240.0               4.0
4296      257.0               4.0
4297      257.0               4.0

In [28]:
#7.3 Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 9 rows)
data[data.Make == 'Lotus'][['Engine HP', 'Engine Cylinders']].drop_duplicates()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [29]:
#7.4 Get the underlying NumPy array. Let's call it 'X'
X = data[data.Make == 'Lotus'][['Engine HP', 'Engine Cylinders']].drop_duplicates().values
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [30]:
#7.5 Compute matrix-matrix multiplication between the transpose of X and X.
#      To get the transpose, use X.T
#      Let's call the result XTX

In [31]:
XT = X.T
XT

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [32]:
XTX = XT.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [33]:
#7.6  Invert XTX
#     инвертирование матрицы 'XTX'
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [34]:
#7.7 Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [35]:
#7.8 Multiply the inverse of 'XTX' with the transpose of 'X', and then multiply the result by 'y'
#     Call the result 'w'

#     w = (XT*X)^^(-1)*XT*y

w = XTX_inv.dot(X.T).dot(y)
w

array([  4.59494481, -63.56432501])

In [36]:
w[0].round(4)

4.5949